---
host1:
    hostname: 127.0.0.1
    username: test
    password: test
    groups:
        - test
    data:
        plateform: cisco
        num_ports: 12

host2:
    hostname: 127.0.0.2
    username: test
    password: test
    groups:
        - test
    data:
        plateform: cisco
        num_ports: 12

host3:
    hostname: 127.0.0.3
    username: test
    password: test
    groups:
        - test
    data:
        plateform: cisco
        num_ports: 12